# Generated by Django 4.1.5 on 2023-01-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Specious Name')),
                ('Photo1', models.ImageField(blank=True, null=True, upload_to='Products Photos')),
                ('Photo2', models.ImageField(blank=True, null=True, upload_to='Products Photos')),
                ('Photo3', models.ImageField(blank=True, null=True, upload_to='Products Photos')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plant_app.productscategory')),
            ],
        ),
    ]
